### ISSUE TITLE
Misleading API

### ISSUE THREAD

**Issue by paragonie-scott** [popphp/pop-crypt#1]
* One-way cryptographic transformations aren't "encryption hashing", they're just hashes.
* Two-way cryptographic transformations aren't "hashing", they're encryption.

Recommended reading: [an introduction to cryptography terms and concepts](https://paragonie.com/blog/2015/08/you-wouldnt-base64-a-password-cryptography-decoded).

Also, [don't use mcrypt](https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong).

**Comment by rugk** [comment]
Also: https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own

**Comment by nicksagona** [comment]
Hey - appreciate the input. I'm currently working on updating/upgrading many of the components for Pop for the next release. This one is actually on the chopping block as it was mostly from before PHP 5.3. I'm thinking about doing away with it in favor of using what's now natively available in PHP. I'll keep you posted.

**Comment by rugk** [comment]
> I'm thinking about doing away with it in favor of using what's now natively available in PHP.

That's a good decision. :smiley:
